arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
# [TODO: Investigate if bellow configuration is needed]
# use-escaping: true
# synthetic-package: false
