name: demo_app
description: Demo App made with Flutter showcasing clean architecture
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  _bom:
    path: packages/_bom
  _core:
    path: packages/_core
  _env:
    path: packages/_env
  api_repo:
    path: packages/api_repo
  bloc:
  device_preview: ^1.2.0
  envied:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  freezed_annotation:
  get_it:
  google_sign_in:
  intl:
  json_annotation:
  powersync_repo:
    path: packages/powersync_repo

dev_dependencies:
  bloc_test:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  freezed:
  mocktail:
  very_good_analysis:

flutter:
  uses-material-design: true
  generate: true
