// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmFElhMheS8zBuGmvPNi15gJskFmuq1k4',
    appId: '1:904324906972:web:7a55ba4d8dfef9b528d919',
    messagingSenderId: '904324906972',
    projectId: 'flutter-demo-dev-bcf83',
    authDomain: 'flutter-demo-dev-bcf83.firebaseapp.com',
    storageBucket: 'flutter-demo-dev-bcf83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSz1mdRGcF4buI6vu4mnx60Ve5gl0fkHs',
    appId: '1:904324906972:android:8d4a2c5084be931028d919',
    messagingSenderId: '904324906972',
    projectId: 'flutter-demo-dev-bcf83',
    storageBucket: 'flutter-demo-dev-bcf83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlvMMgEtoahOMuaXxx44Oqb6W-W7DNT-0',
    appId: '1:904324906972:ios:3706cfa6fadb99df28d919',
    messagingSenderId: '904324906972',
    projectId: 'flutter-demo-dev-bcf83',
    storageBucket: 'flutter-demo-dev-bcf83.firebasestorage.app',
    iosClientId: '904324906972-a40ul1sm1e0j7g842lv9f6ugg6u0b4hd.apps.googleusercontent.com',
    iosBundleId: 'com.lecnier.flutterDemo',
  );

}