name: _env
description: Manage environment variables
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  _bom:
    path: ../_bom
  envied:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  envied_generator:
  flutter_test:
    sdk: flutter
  mocktail:
  very_good_analysis:
